### ISSUE TITLE
Chapter 12: tacocloud-mongo has MySQL database URL defined in application.yml

### ISSUE THREAD

**Issue by filibie** [habuma/spring-in-action-6-samples#24]
When viewing chapter 12 taco cloud code (mongodb version) you can find a datasource URL defined in application.yml, the URL points to MySQL database, whereas it should point to mongo database.

```
---
spring:
  profiles: prod

  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacouser
    password: tacopassword
```

[https://github.com/habuma/spring-in-action-6-samples/blob/main/ch12_13/tacocloud-mongodb/tacocloud/src/main/resources/application.yml](https://github.com/habuma/spring-in-action-6-samples/blob/main/ch12_13/tacocloud-mongodb/tacocloud/src/main/resources/application.yml)
